version: '3.8'

services:
  db:
    image: 'postgres:14-alpine'
    container_name: doggotime-db
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      - DATABASE_URL=postgres://postgres:postgres2021@localhost:5432/doggotime